on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Name of the target environment.    
      ref:  
        type: string
        required: true
        description: The tag or SHA to checkout.

jobs:
  compile_dataform:
    name: Compile Dataform
    runs-on: ubuntu-latest
    container:
      image: node:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dataform CLI
      run: |
        npm install -g @dataform/cli

    - name: Compile Dataform project
      run: |
        dataform compile
  
  lint_dags:
    name: Lint Airflow DAGs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install flake8

    - name: Lint DAGs
      run: |
        flake8 ./dags

  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pwd && ls && pip install -r requirements.txt

    - name: Init Airflow db
      run: |
        airflow db init

    - name: Run unit tests
      run: |
        python -m unittest discover -s ./dags